---
- name: Install Neovim
  homebrew:
    name: neovim
    state: present

- name: Create Neovim config directory
  file:
    path: ~/.config/nvim
    state: directory

- name: Clone Neovim config from GitHub
  git:
    repo: "https://github.com/ekn-j/nvim"
    dest: ~/.config/nvim
    clone: yes
    update: yes
  when: "'ekn-j/nvim.git' != 'https://github.com/ekn-j/nvim'"
  # Replace the above URL with your actual GitHub repo URL
